language: java

env:
  - DB=sqlserver

jdk:
  - openjdk7

sqlserver:
  database: empi
  username: sa
  password : 123456
  encoding: utf8

install:
  - mvn install -Dmaven.test.skip=true

before_script:
  - cd empi-web
  - mvn clean
  - mvn db:data
  - cd ..

script:
  - cd base-common
  - mvn test
  - cd ..
  - cd empi-web
  - mvn test -Pit

notifications:
  email:
    - wu_zhijun@msn.com